### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Lylb** [anita-hu/MSAF#11]
[CMU-MultimodalSDK @ fd18d71](https://github.com/A2Zadeh/CMU-MultimodalSDK/tree/fd18d71dc26b4d834480306c2ce1a903b8a8ff70)   is error

**Comment by anita-hu** [comment]
They moved to https://github.com/ecfm/CMU-MultimodalSDK

**Comment by Lylb** [comment]
With this address,I have the problem:
Traceback (most recent call last):
  File "dataset_prep.py", line 130, in <module>
    dataset = md.mmdataset(recipe)
  File "/root/autodl-tmp/MSAF-master/cmu_mosei/mmsdk/mmdatasdk/dataset/dataset.py", line 28, in __init__
    self.computational_sequences[entry]=computational_sequence(address,destination)
  File "/root/autodl-tmp/MSAF-master/cmu_mosei/mmsdk/mmdatasdk/computational_sequence/computational_sequence.py", line 32, in __init__
    h5handle,data,metadata=self._initialize(resource,destination)
  File "/root/autodl-tmp/MSAF-master/cmu_mosei/mmsdk/mmdatasdk/computational_sequence/computational_sequence.py", line 92, in _initialize
    return readCSD(self.mainFile)
  File "/root/autodl-tmp/MSAF-master/cmu_mosei/mmsdk/mmdatasdk/computational_sequence/file_ops.py", line 14, in readCSD
    log.error("%s file not found, please check the path ..."%resource,error=True)
  File "/root/autodl-tmp/MSAF-master/cmu_mosei/mmsdk/mmdatasdk/log/log.py", line 18, in error
    action("%s%s"%(msgstart,msgstring))
  File "/root/autodl-tmp/MSAF-master/cmu_mosei/mmsdk/mmdatasdk/log/log.py", line 17, in <lambda>
    action,msgstart=(lambda x:(_ for _ in ()).throw(errorType(x)),"<Error>: ") if error else (lambda x:sys.stdout.write(str(x)+'\n'),bcolors.WARNING+bcolors.BOLD+"<Warning>: "+bcolors.ENDC)
  File "/root/autodl-tmp/MSAF-master/cmu_mosei/mmsdk/mmdatasdk/log/log.py", line 17, in <genexpr>
    action,msgstart=(lambda x:(_ for _ in ()).throw(errorType(x)),"<Error>: ") if error else (lambda x:sys.stdout.write(str(x)+'\n'),bcolors.WARNING+bcolors.BOLD+"<Warning>: "+bcolors.ENDC)
RuntimeError: <Error>: ./CMU_MOSEI/csd/CMU_MOSEI_VisualFacet42.csd file not found, please check the path ...
