### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Lylb** [anita-hu/MSAF#13]
With this address,I have the problem:
Traceback (most recent call last):
File "dataset_prep.py", line 130, in
dataset = md.mmdataset(recipe)
File "/root/autodl-tmp/MSAF-master/cmu_mosei/mmsdk/mmdatasdk/dataset/dataset.py", line 28, in init
self.computational_sequences[entry]=computational_sequence(address,destination)
File "/root/autodl-tmp/MSAF-master/cmu_mosei/mmsdk/mmdatasdk/computational_sequence/computational_sequence.py", line 32, in init
h5handle,data,metadata=self.initialize(resource,destination)
File "/root/autodl-tmp/MSAF-master/cmu_mosei/mmsdk/mmdatasdk/computational_sequence/computational_sequence.py", line 92, in initialize
return readCSD(self.mainFile)
File "/root/autodl-tmp/MSAF-master/cmu_mosei/mmsdk/mmdatasdk/computational_sequence/file_ops.py", line 14, in readCSD
log.error("%s file not found, please check the path ..."%resource,error=True)
File "/root/autodl-tmp/MSAF-master/cmu_mosei/mmsdk/mmdatasdk/log/log.py", line 18, in error
action("%s%s"%(msgstart,msgstring))
File "/root/autodl-tmp/MSAF-master/cmu_mosei/mmsdk/mmdatasdk/log/log.py", line 17, in
action,msgstart=(lambda x:( for _ in ()).throw(errorType(x)),": ") if error else (lambda x:sys.stdout.write(str(x)+'\n'),bcolors.WARNING+bcolors.BOLD+": "+bcolors.ENDC)
File "/root/autodl-tmp/MSAF-master/cmu_mosei/mmsdk/mmdatasdk/log/log.py", line 17, in
action,msgstart=(lambda x:( for _ in ()).throw(errorType(x)),": ") if error else (lambda x:sys.stdout.write(str(x)+'\n'),bcolors.WARNING+bcolors.BOLD+": "+bcolors.ENDC)
RuntimeError: : ./CMU_MOSEI/csd/CMU_MOSEI_VisualFacet42.csd file not found, please check the path ...

**Comment by Zhan9YC** [comment]
the issue have resolved?
